/'
tag::class-diagram[]
'/
@startuml class-diagram

    class singleton {
        - {static} : m_id_counter : int
        - m_id : int
        - {static} m_instance : singleton*
        - constructor()
        + {static} get_intance() : singleton&
        + get_id() : int
    }

@enduml
/'
end::class-diagram[]
'/
